

name: SUMMIT-API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_URL: ${{ secrets.URL_SUMMIT_STAGING }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14.17.0"
    - run: npm install
    - run: npm run build --if-present
    - name: zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./bundle.zip ./
    - name: default deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.MVS_AWS_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.MVS_AWS_SECRET_ACCESS_KEY }}
        aws_region: us-west-1
        function_name: summit
        zip_file: bundle.zip
    